apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-server-ci
  name: go-server-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server-ci
  template:
    metadata:
      labels:
        app: go-server-ci
    spec:
      containers:
      - image: ghcr.io/2023-4400-exp/4401-go-server-ci:5b671c47bd801321184bbdff6b15a4293d8cfd47@sha256:78b26e56b12126ba27c85c7dee7493b6f2226483486801640b43c60e179ad4c6
        name: go-server-ci
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-server-ci
  name: go-server-ci
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-server-ci
  type: NodePort